spring:
  application:
    name: RiskNarrative

  jackson:
    property-naming-strategy: SNAKE_CASE

    jpa:
        generate-ddl: true
        show-sql: true

truproxy:
  base:
    url: https://exercise.trunarrative.cloud/